# Site settings
title: shiftrequest
description: My Domain & Galleries - NinA[rt] + Î£(aspects)
url: "https://shiftrequest.art"
baseurl: ""

# Exclude from processing
exclude:
  - README.md
  - deploy.sh
  - s3_website.yml
  - Gemfile
  - Gemfile.lock
