# Site settings
title: shiftrequest
description: My Domain & Galleries - NinA[rt] + Î£(aspects)
url: "https://shiftrequest.art"
baseurl: ""

# Include .well-known directory for Chrome DevTools
include:
  - .well-known
  - gpg-public-key.asc

# Exclude from processing
exclude:
  - README.md
  - deploy.sh
  - s3_website.yml
  - Gemfile
  - Gemfile.lock
